### ISSUE TITLE
[Feature Request] Support AWS_SHARED_CREDENTIALS_FILE environment variable

### ISSUE THREAD

**Issue by hegyre** [tomaszkiewicz/aws-cli-adfs#5]
Hello,

Using python 2.7.13

On Windows Powershell, we can have a `HOME` environment variable, which could be different from `"%USERPROFILE%\.aws\credentials"`

Example of `env` command from within Powershell:
```
...
HOME=/c/somefolder
HOMEDRIVE=U:
HOMEPATH=\
HOMESHARE=\\some_share\user$
...
```
whist my `"%USERPROFILE%\.aws\credentials"` points to `'C:\Users\user\.aws'`

Your python script currently uses the `HOME` env variable, which is OK (with `expanduser` function: https://docs.python.org/2/library/os.path.html#os.path.expanduser)
However, Terraform for instance uses `'C:\Users\user\.aws'` by default (except if I set `AWS_SHARED_CREDENTIALS_FILE` env variable to `"$Env:HOME\.aws\credentials"`

It would be good if you also support `AWS_SHARED_CREDENTIALS_FILE` env variable, like you do for the `AWS_PROFILE` env variable.
Ref: https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html

Something like the below should works:

`aws_credentials_file = os.environ['AWS_SHARED_CREDENTIALS_FILE'] if 'AWS_SHARED_CREDENTIALS_FILE' in os.environ else '~/.aws/credentials'`

The `aws_config_file` python variable would then be in the same folder as `aws_credentials_file` variable.
Something like:
`aws_config_file = os.path.dirname(aws_credentials_file) + '/config'`

**Comment by tomaszkiewicz** [comment]
Hi, I've just added the feature you requested, please update to the 0.1.6 version :)

**Comment by hegyre** [comment]
Thank you for your prompt update @tomaszkiewicz 

Works fine!
